export const environment = {
  production: true,
  API_KEY:
    'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMThhZDRhNTBkZDUyNDMzYjI0Y2M5M2FkOGE3NDRlZiIsIm5iZiI6MTcyNzgwMzIxMC4zNzQwMTMsInN1YiI6IjY2ZmMyZTNkZjJiOWM5N2MxZGQ2NGE4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.ZwxlJs0kpIIyWu9UCF5gp7VmwWBuAGy-98wbQJwpldM',
};
